package com.github.MCreeper12731;

public enum Interaction {

    LEFT_CLICK_ANY,
    LEFT_CLICK_AIR,
    LEFT_CLICK_BLOCK,
    RIGHT_CLICK_ANY,
    RIGHT_CLICK_AIR,
    RIGHT_CLICK_BLOCK,
    SNEAK_LEFT_CLICK_ANY,
    SNEAK_LEFT_CLICK_AIR,
    SNEAK_LEFT_CLICK_BLOCK,
    SNEAK_RIGHT_CLICK_ANY,
    SNEAK_RIGHT_CLICK_AIR,
    SNEAK_RIGHT_CLICK_BLOCK,

}
